### ISSUE TITLE
Can't install pods

### ISSUE THREAD

**Issue by ThasianX** [HabitRPG/habitrpg-ios#857]
I'm getting the following error when trying to install pod files. I executed the command for installing cocoapods keys before so it should work. But it's not.

```
(base) Kevins-MacBook-Pro:habitica-ios kevinli$ pod install
ERROR: Can't find header dir for ruby. Exiting...

---------------------------------------------
Error loading the plugin `cocoapods-keys-2.1.0`.

SystemExit - ERROR: Can't find header dir for ruby. Exiting...
/Library/Ruby/Gems/2.3.0/gems/RubyInline-3.12.5/lib/inline.rb:567:in `abort'
/Library/Ruby/Gems/2.3.0/gems/RubyInline-3.12.5/lib/inline.rb:567:in `build'
/Library/Ruby/Gems/2.3.0/gems/RubyInline-3.12.5/lib/inline.rb:859:in `inline'
/Library/Ruby/Gems/2.3.0/gems/osx_keychain-1.0.2/lib/osx_keychain.rb:17:in `<class:OSXKeychain>'
/Library/Ruby/Gems/2.3.0/gems/osx_keychain-1.0.2/lib/osx_keychain.rb:6:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-keys-2.1.0/lib/keyring.rb:1:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-keys-2.1.0/lib/cocoapods_plugin.rb:1:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:94:in `block in safe_activate_and_require'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:94:in `each'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:94:in `safe_activate_and_require'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:31:in `block in load_plugins'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:30:in `map'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:30:in `load_plugins'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.3/lib/claide/command.rb:326:in `block in run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.3/lib/claide/command.rb:325:in `each'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.3/lib/claide/command.rb:325:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
---------------------------------------------

[!] Your Podfile requires that the plugin `cocoapods-keys` be installed. Please install it and try installation again.

```

**Comment by phillipthelen** [comment]
Did you upgrade to macOS Catalina? That breaks some things. Reinstalling things fixed them iirc. (But there might be some extra steps necessary)

--  
Phillip Thelen
Sent with Airmail

**Comment by ThasianX** [comment]
I'm still on Mojave. Pretty sure something's wrong with my Ruby.
